language: node_js

matrix:
  include:
    - node_js: 8
      env: RELEASE="true"
    - node_js: 9
    - node_js: 10

deploy:
  provider: npm
  email: npmjs@paysera.com
  api_key:
    secure: UPXSynZo3qQrQq9Nln6PSiE/zlSJXNF9unUDNYDW9CpmXMrSHLhFV6YZnDUAwLcxIGtn2azOw7R2FZCgciG9LsbsE5WGYque2hCmlv7kSeBbJ9fgIzEb7g5GKS4i7mRs9vholxmZ1YyJeEITzsKHqzFi2fqcvdY6i1/MMf8oN8/pwT8nbpeJef1IZ6bdG58229SjKrlU4wp+VPiy9lqIbROe1ZE9/2K2bLmSoB4nf9BZVxWHGmWs9ZSUlIOEJ0Dd+xzZWPjR2DsSu6ELqNh7Ak1mxjl270B679OcrmFLNKXfqCdfa/xWD2mjmmXOEQ1B9bH1ajXwSLm1wUTfxjVxb1/YtB36aaqx8Nqv0syZPAYrfTkxglADHmD/whZU3+TeAQRsM4IXUTSm4IQOXx1nT811ImA/8+SnX2ofLp+0Gj3Uh+W+C/EeHEhpb6UIZRBNXrkAPxAgu1RbBjSEP7O9X0ul39NbXMqOJN+yN7YVjKK6w5HAPO44PBC1kwi3Yu2L9Is9zFopOcIYA7ChQO2h+Ipgqr5SRWhBSWeJG8p6/5+YTgNt1Ifq8T9dzXRUj3XvitPy1HVAxJfSk6/4X+aPzJTatwfQKjOT6gOluiAYbPu6Wx7d/FbauD16sWWIK8p3hSUCDNJP/1kVc2N5F6iYtVDEBURDaBn6tcwlLyCZ//M=
  on:
    tags: true
    repo: paysera/js-lib-redux-state-restore
    condition: "$RELEASE = true"
  skip_cleanup: true

script:
  - npm run test:coverage && cat ./coverage/lcov.info | node_modules/.bin/coveralls
